name: Welcome Workflow

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo 'Welcome to the Skills Hello GitHub Actions repository!'
